name: Run Bot 5 (Trivia Bot)

on:
  schedule:
    - cron: '0 14 * * *'  # Every day at 10am EST
  workflow_dispatch:      # Optional: lets you run manually from GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot5
      run: python bots/bot5/bot.py
