name: Run Bot 6 (Rookie Bot)

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 10 PM EST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot6
      run: python bots/bot6/bot.py
