name: Run Bot 8 (All-Time Leaders)

on:
  schedule:
    - cron: '0 16 * * 5' 
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot8
      run: python bots/bot8/bot.py
