name: Run Bot 9 (Draft Throwback Bot)

on:
  schedule:
    - cron: '0 15 */2 * *'  # Every Saturday at 11am EST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot9
      run: python bots/bot9/bot.py
